[book]
authors = ["Patrick O'Doherty"]
language = "en"
multilingual = false
src = "src"
title = "Patrick's Lab Notebook"

[output.html]
git-repository-url = "https://github.com/patrickod/notebook"
site-url = "/notebook/"
